name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Устанавливаем Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting css
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      - name: screenshot testing
        run: npm run test:ui:ci

      - name: Upload Loki results if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: loki-differences
          path: .loki/
          retention-days: 7
